// import React, { useState, useEffect } from "react";
// import { useParams, useNavigate } from "react-router";
// import { jsPDF } from "jspdf";
// import {
//   ArrowLeft,
//   Download,
//   Calendar,
//   Clock,
//   FileText,
//   MessageSquare,
//   CheckSquare,
//   BarChart2,
// } from "lucide-react";
// import { getMeetingDetails } from "../../api/meet";
// import { useAuth } from "../hooks/useAuth";

// import Header from "../layout/Header";
// import Sidebar from "../layout/Sidebar";

// const MeetingDetails = () => {
//   const { id } = useParams();
//   const navigate = useNavigate();
//   const { user, setUser } = useAuth();
//   const [sidebarOpen, setSidebarOpen] = useState(false);
//   const [activeTab, setActiveTab] = useState("history");
//   const [meeting, setMeeting] = useState(null);
//   const [loading, setLoading] = useState(true);

//   useEffect(() => {
//     const fetchMeeting = async () => {
//       try {
//         const res = await getMeetingDetails(id);
//         const data = res.data || res;
//         setMeeting(data);
//       } catch (err) {
//         console.error("Failed to load meeting", err);
//         alert("Could not load meeting details.");
//         navigate("/");
//       } finally {
//         setLoading(false);
//       }
//     };
//     fetchMeeting();
//   }, [id, navigate]);

//   const handleExport = () => {
//     if (!meeting) return;

//     const doc = new jsPDF();
//     const pageWidth = doc.internal.pageSize.getWidth();
//     const margin = 15;
//     const maxLineWidth = pageWidth - margin * 2;
//     let yPos = 20;
//     const addText = (text, fontSize = 10, isBold = false) => {
//       doc.setFontSize(fontSize);
//       doc.setFont("helvetica", isBold ? "bold" : "normal");

//       const lines = doc.splitTextToSize(text, maxLineWidth);
//       doc.text(lines, margin, yPos);

//       yPos += lines.length * (fontSize * 0.5) + 5;
//     };

//     addText(meeting.title || "Meeting Summary", 22, true);
//     yPos += 5;

//     addText(`Date: ${new Date(meeting.createdAt).toLocaleDateString()}`, 10);
//     addText(`Duration: ${meeting.duration || "Unknown"}`, 10);
//     yPos += 10;

//     addText("Executive Summary", 14, true);
//     addText(meeting.summary || "No summary available.", 11);
//     yPos += 10;

//     addText("Action Items", 14, true);
//     if (meeting.actionItems && meeting.actionItems.length > 0) {
//       meeting.actionItems.forEach((item) => {
//         const taskText = typeof item === "string" ? item : item.task;
//         addText(`• ${taskText}`, 11);
//       });
//     } else {
//       addText("No action items detected.", 11);
//     }
//     yPos += 10;

//     addText("Transcript Snippet (First 500 chars)", 14, true);
//     const transcriptSnippet = meeting.transcript
//       ? meeting.transcript.substring(0, 500) + "..."
//       : "No transcript.";

//     addText(transcriptSnippet, 10);

//     doc.setFontSize(8);
//     doc.setTextColor(150);
//     doc.text("Generated by AI Meeting Assistant", margin, 280);

//     doc.save(`${meeting.title || "meeting_report"}.pdf`);
//   };

//   const handleLogout = () => {
//     setUser(null);
//   };

//   if (loading) {
//     return (
//       <div className="min-h-screen bg-gray-50 flex items-center justify-center">
//         <div className="animate-pulse flex flex-col items-center">
//           <div className="h-12 w-12 bg-indigo-200 rounded-full mb-4"></div>
//           <div className="h-4 w-32 bg-gray-200 rounded"></div>
//         </div>
//       </div>
//     );
//   }

//   if (!meeting) return null;

//   return (
//     <div className="min-h-screen bg-gray-50">
//       <Header
//         sidebarOpen={sidebarOpen}
//         setSidebarOpen={setSidebarOpen}
//         userEmail={user?.email}
//         onLogout={handleLogout}
//       />

//       <div className="flex max-w-7xl mx-auto">
//         <Sidebar
//           isOpen={sidebarOpen}
//           setSidebarOpen={setSidebarOpen}
//           activeTab={activeTab}
//           setActiveTab={(tab) => {
//             if (tab === "live") navigate("/"); // Redirect if they click "Live"
//           }}
//           meetingHistory={[]} // Pass empty or cached list if you want sidebar links
//         />

//         <main className="flex-1 p-6 lg:p-10">
//           {/* --- TOP BAR --- */}
//           <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
//             <div className="flex items-center gap-4">
//               <button
//                 onClick={() => navigate("/")}
//                 className="p-2 hover:bg-gray-200 rounded-full transition-colors"
//               >
//                 <ArrowLeft className="w-6 h-6 text-gray-600" />
//               </button>
//               <div>
//                 <h1 className="text-2xl font-bold text-gray-800">
//                   {meeting.title || "Untitled Meeting"}
//                 </h1>
//                 <div className="flex items-center gap-4 text-sm text-gray-500 mt-1">
//                   <span className="flex items-center gap-1">
//                     <Calendar className="w-4 h-4" />
//                     {new Date(meeting.createdAt).toLocaleDateString()}
//                   </span>
//                   <span className="flex items-center gap-1">
//                     <Clock className="w-4 h-4" />
//                     {meeting.duration || "Unknown Duration"}
//                   </span>
//                 </div>
//               </div>
//             </div>

//             {/* ✅ EXPORT BUTTON (Moved Here) */}
//             <button
//               onClick={handleExport}
//               className="flex items-center gap-2 bg-indigo-600 text-white px-5 py-2.5 rounded-xl font-semibold hover:bg-indigo-700 transition-colors shadow-sm"
//             >
//               <Download className="w-4 h-4" />
//               Export PDF
//             </button>
//           </div>

//           {/* --- DASHBOARD GRID --- */}
//           <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
//             {/* LEFT COLUMN: Summary & Actions */}
//             <div className="lg:col-span-2 space-y-6">
//               {/* Summary Card */}
//               <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
//                 <div className="flex items-center gap-2 mb-4">
//                   <FileText className="w-5 h-5 text-indigo-600" />
//                   <h3 className="text-lg font-semibold text-gray-800">
//                     Executive Summary
//                   </h3>
//                 </div>
//                 <p className="text-gray-600 leading-relaxed">
//                   {meeting.summary || "No summary available."}
//                 </p>
//               </div>

//               {/* Transcript Card */}
//               <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
//                 <div className="flex items-center gap-2 mb-4">
//                   <MessageSquare className="w-5 h-5 text-indigo-600" />
//                   <h3 className="text-lg font-semibold text-gray-800">
//                     Full Transcript
//                   </h3>
//                 </div>
//                 <div className="bg-gray-50 p-4 rounded-xl border border-gray-200 h-96 overflow-y-auto whitespace-pre-wrap text-sm text-gray-700 font-mono leading-relaxed">
//                   {meeting.transcript || "No transcript available."}
//                 </div>
//               </div>
//             </div>

//             {/* RIGHT COLUMN: Actions & Sentiment */}
//             <div className="space-y-6">
//               {/* Action Items */}
//               <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
//                 <div className="flex items-center gap-2 mb-4">
//                   <CheckSquare className="w-5 h-5 text-green-600" />
//                   <h3 className="text-lg font-semibold text-gray-800">
//                     Action Items
//                   </h3>
//                 </div>
//                 {meeting.actionItems && meeting.actionItems.length > 0 ? (
//                   <ul className="space-y-3">
//                     {meeting.actionItems.map((item, idx) => (
//                       <li
//                         key={idx}
//                         className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg"
//                       >
//                         <div className="mt-1 min-w-[16px] min-h-[16px] border-2 border-green-500 rounded flex items-center justify-center">
//                           <div className="w-2 h-2 bg-green-500 rounded-full"></div>
//                         </div>
//                         <span className="text-sm text-gray-700">
//                           {/* Handle Object vs String data structure */}
//                           {typeof item === "string" ? item : item.task}
//                         </span>
//                       </li>
//                     ))}
//                   </ul>
//                 ) : (
//                   <p className="text-sm text-gray-500 italic">
//                     No action items detected.
//                   </p>
//                 )}
//               </div>

//               {/* Sentiment Analysis */}
//               <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
//                 <div className="flex items-center gap-2 mb-4">
//                   <BarChart2 className="w-5 h-5 text-purple-600" />
//                   <h3 className="text-lg font-semibold text-gray-800">
//                     Sentiment
//                   </h3>
//                 </div>
//                 {meeting.sentiment ? (
//                   <div className="space-y-4">
//                     <div>
//                       <div className="flex justify-between text-xs mb-1 text-gray-600">
//                         <span>Positive</span>
//                         <span>{meeting.sentiment.positive}%</span>
//                       </div>
//                       <div className="w-full bg-gray-100 rounded-full h-2">
//                         <div
//                           className="bg-green-500 h-2 rounded-full"
//                           style={{ width: `${meeting.sentiment.positive}%` }}
//                         ></div>
//                       </div>
//                     </div>
//                     <div>
//                       <div className="flex justify-between text-xs mb-1 text-gray-600">
//                         <span>Neutral</span>
//                         <span>{meeting.sentiment.neutral}%</span>
//                       </div>
//                       <div className="w-full bg-gray-100 rounded-full h-2">
//                         <div
//                           className="bg-gray-400 h-2 rounded-full"
//                           style={{ width: `${meeting.sentiment.neutral}%` }}
//                         ></div>
//                       </div>
//                     </div>
//                     <div>
//                       <div className="flex justify-between text-xs mb-1 text-gray-600">
//                         <span>Negative</span>
//                         <span>{meeting.sentiment.negative}%</span>
//                       </div>
//                       <div className="w-full bg-gray-100 rounded-full h-2">
//                         <div
//                           className="bg-red-500 h-2 rounded-full"
//                           style={{ width: `${meeting.sentiment.negative}%` }}
//                         ></div>
//                       </div>
//                     </div>
//                   </div>
//                 ) : (
//                   <p className="text-sm text-gray-500 italic">
//                     Sentiment data unavailable.
//                   </p>
//                 )}
//               </div>
//             </div>
//           </div>
//         </main>
//       </div>
//     </div>
//   );
// };

// export default MeetingDetails;

 // Added

import React, { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router";
import { jsPDF } from "jspdf";
import {
  ArrowLeft,
  Download,
  Calendar,
  Clock,
  FileText,
  MessageSquare,
  CheckSquare,
  BarChart2,
  Users,
  HelpCircle,
  ClipboardList,
} from "lucide-react";

import { getMeetingDetails } from "../../api/meet";
import { useAuth } from "../hooks/useAuth";
import Header from "../layout/Header";
import Sidebar from "../layout/Sidebar";

const MeetingDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user, setUser } = useAuth();

  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [meeting, setMeeting] = useState(null);
  const [loading, setLoading] = useState(true);

  /* ================= FETCH ================= */
  useEffect(() => {
    const fetchMeeting = async () => {
      try {
        const res = await getMeetingDetails(id);
        setMeeting(res.data || res);
      } catch (err) {
        console.error(err);
        alert("Failed to load meeting");
        navigate("/");
      } finally {
        setLoading(false);
      }
    };
    fetchMeeting();
  }, [id, navigate]);

  /* ================= PDF EXPORT ================= */
  const handleExport = () => {
    if (!meeting) return;

    const doc = new jsPDF();
    const margin = 15;
    const pageWidth = doc.internal.pageSize.getWidth();
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    const write = (text, size = 10, bold = false) => {
      doc.setFont("helvetica", bold ? "bold" : "normal");
      doc.setFontSize(size);
      const lines = doc.splitTextToSize(text, maxWidth);
      doc.text(lines, margin, y);
      y += lines.length * (size * 0.5) + 4;
    };

    write(meeting.title || "Meeting Report", 20, true);
    y += 4;

    write(`Date: ${new Date(meeting.createdAt).toLocaleDateString()}`);
    write(`Duration: ${meeting.duration || "Unknown"}`);
    y += 6;

    write("Executive Summary", 14, true);
    write(meeting.executiveSummary || "N/A", 11);

    write("Detailed Summary", 14, true);
    write(meeting.detailedSummary || "N/A", 11);

    write("Decisions", 14, true);
    (meeting.minutesOfMeeting?.decisions || []).forEach(d =>
      write(`• ${d}`, 11)
    );

    write("Action Items", 14, true);
    (meeting.minutesOfMeeting?.actionItems || []).forEach(a =>
      write(`• ${a.task} — ${a.assignee} (${a.deadline || "TBD"})`, 11)
    );

    doc.setFontSize(8);
    doc.text("Generated by AI Meeting Assistant", margin, 285);

    doc.save(`${meeting.title || "meeting"}.pdf`);
  };

  const handleLogout = () => setUser(null);

  /* ================= LOADING ================= */
  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="animate-pulse text-gray-500">Loading meeting…</div>
      </div>
    );
  }

  if (!meeting) return null;

  /* ================= UI ================= */
  return (
    <div className="min-h-screen bg-gray-50">
      <Header
        sidebarOpen={sidebarOpen}
        setSidebarOpen={setSidebarOpen}
        userEmail={user?.email}
        onLogout={handleLogout}
      />

      <div className="flex max-w-7xl mx-auto">
        <Sidebar isOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />

        <main className="flex-1 p-6 lg:p-10 space-y-8">
          {/* HEADER */}
          <div className="flex justify-between items-center">
            <div className="flex items-center gap-4">
              <button
                onClick={() => navigate("/")}
                className="p-2 rounded-full hover:bg-gray-200"
              >
                <ArrowLeft />
              </button>
              <div>
                <h1 className="text-2xl font-bold">{meeting.title}</h1>
                <div className="text-sm text-gray-500 flex gap-4">
                  <span className="flex items-center gap-1">
                    <Calendar size={14} />
                    {new Date(meeting.createdAt).toLocaleDateString()}
                  </span>
                  <span className="flex items-center gap-1">
                    <Clock size={14} />
                    {meeting.duration || "Unknown"}
                  </span>
                </div>
              </div>
            </div>

            <button
              onClick={handleExport}
              className="flex items-center gap-2 bg-indigo-600 text-white px-5 py-2 rounded-xl hover:bg-indigo-700"
            >
              <Download size={16} />
              Export PDF
            </button>
          </div>

          {/* EXEC SUMMARY */}
          <Section icon={FileText} title="Executive Summary">
            {meeting.executiveSummary || "No executive summary available."}
          </Section>

          {/* DETAILED SUMMARY */}
          <Section icon={ClipboardList} title="Detailed Summary">
            <p className="whitespace-pre-line">
              {meeting.detailedSummary || "No detailed summary available."}
            </p>
          </Section>

          {/* MOM */}
          <div className="bg-white p-6 rounded-2xl shadow-sm space-y-6">
            <h3 className="text-lg font-semibold">Minutes of Meeting</h3>

            <MoMBlock icon={Users} title="Attendees">
              <ul className="list-disc list-inside">
                {(meeting.minutesOfMeeting?.attendees || []).map((a, i) => (
                  <li key={i}>{a}</li>
                ))}
              </ul>
            </MoMBlock>

            <MoMBlock icon={MessageSquare} title="Topics Discussed">
              <div className="space-y-3">
                {(meeting.minutesOfMeeting?.topicsDiscussed || []).map(
                  (t, i) => (
                    <div key={i} className="bg-gray-50 p-3 rounded">
                      <p className="font-medium">{t.topic}</p>
                      <p className="text-sm text-gray-600">{t.discussion}</p>
                    </div>
                  )
                )}
              </div>
            </MoMBlock>

            <MoMBlock icon={CheckSquare} title="Decisions">
              <ul className="list-disc list-inside">
                {(meeting.minutesOfMeeting?.decisions || []).map((d, i) => (
                  <li key={i}>{d}</li>
                ))}
              </ul>
            </MoMBlock>

            <MoMBlock icon={HelpCircle} title="Open Questions">
              <ul className="list-disc list-inside">
                {(meeting.minutesOfMeeting?.openQuestions || []).map((q, i) => (
                  <li key={i}>{q}</li>
                ))}
              </ul>
            </MoMBlock>
          </div>

          {/* ACTION ITEMS */}
          <Section icon={CheckSquare} title="Action Items">
            <ul className="space-y-3">
              {(meeting.minutesOfMeeting?.actionItems || []).map((a, i) => (
                <li key={i} className="bg-gray-50 p-3 rounded">
                  <p className="font-medium">{a.task}</p>
                  <p className="text-xs text-gray-500">
                    {a.assignee} · {a.deadline || "TBD"}
                  </p>
                </li>
              ))}
            </ul>
          </Section>

          {/* SENTIMENT */}
          <Section icon={BarChart2} title="Sentiment">
            {["positive", "neutral", "negative"].map((k) => (
              <Progress
                key={k}
                label={k}
                value={meeting.sentiment?.[k] || 0}
              />
            ))}
          </Section>

          {/* TRANSCRIPT */}
          <Section icon={MessageSquare} title="Full Transcript">
            <pre className="bg-gray-50 p-4 rounded max-h-96 overflow-y-auto text-sm">
              {meeting.transcript || "No transcript available."}
            </pre>
          </Section>
        </main>
      </div>
    </div>
  );
};

/* ================= REUSABLE ================= */

const Section = ({ icon: Icon, title, children }) => (
  <div className="bg-white p-6 rounded-2xl shadow-sm">
    <div className="flex items-center gap-2 mb-3">
      <Icon className="text-indigo-600" size={18} />
      <h3 className="text-lg font-semibold">{title}</h3>
    </div>
    <div className="text-gray-700">{children}</div>
  </div>
);

const MoMBlock = ({ icon: Icon, title, children }) => (
  <div>
    <div className="flex items-center gap-2 mb-2">
      <Icon size={16} className="text-indigo-600" />
      <h4 className="font-semibold">{title}</h4>
    </div>
    {children}
  </div>
);

const Progress = ({ label, value }) => (
  <div className="mb-3">
    <div className="flex justify-between text-xs mb-1">
      <span className="capitalize">{label}</span>
      <span>{value}%</span>
    </div>
    <div className="h-2 bg-gray-200 rounded">
      <div
        className={`h-2 rounded ${
          label === "positive"
            ? "bg-green-500"
            : label === "negative"
            ? "bg-red-500"
            : "bg-gray-400"
        }`}
        style={{ width: `${value}%` }}
      />
    </div>
  </div>
);

export default MeetingDetails;
